### ISSUE TITLE
Problem z anulowaniem rezerwacji

### ISSUE THREAD

**Issue by LukaszWilk1** [LukaszWilk1/HotelProject#19]
Cos jest nie tak z podstawową obsługą, kod nie chciał się skompilować do póki nie dodalem tam definicji metody anulujRezerwacje, vs zdefiniowalm ja drugi raz, bez tego nie idzie. Zerknij o co tam chodzi. (Plik Podstawowa oobsluga linia 29, bedzie na branchu 16-logowanie)

**Comment by reKOmo** [comment]
Wiesz co ja tam pozmieniałem te sefinicje tych funkcji może coś przeoczyłem, albo przy merge sie zepsuło, zerkene na to
