### ISSUE TITLE
Dodanie wszystkich funkcji pokoi

### ISSUE THREAD

**Issue by LukaszWilk1** [LukaszWilk1/HotelProject#68]
Dodaj te funkcje co mówiłeś żeby dało się dokończyć obsługę recepcji. Jeżeli już są gdzieś na masterze to nie zmerguje ich do siebie na brancha bo są konflikty.

**Comment by reKOmo** [comment]
Już są, to tylko merge zrobie

**Comment by reKOmo** [comment]
Gotowe
